#!/bin/bash --login
#PBS -l walltime=00:30:00
#PBS -l select=1:ncpus=64
#PBS -N _2017_cr_nojoin_no_golay_parallel
#PBS -A d411-training
module load miniconda/python2
echo "loading virtualenv"
source activate qiime1
export TMPDIR=~/qiime_tmp
echo "Picking OTUs with open reference"
echo "Number of cores chosen is $cores"
time pick_closed_reference_otus.py -f -i seqs.fna -o otus_$cores -a -O $cores
source deactivate
