#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N taxon_sil
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1


/usr/bin/time -f %e \
assign_taxonomy.py \
-i ~/18/silva_otus/rep_set.fasta \
-r ~/silva_db/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-t ~/silva_db/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt \
-m blast

source deactivate
