#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=48
#PBS -N diversity_analyses
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e core_diversity_analyses.py \
-o ~/18/core_div \
-i ~/18/closed_otus/otu_table.biom \
-m ~/18/map_corrected.tsv \
-t ~/18/closed_otus/97_otus.tree \
-e 600 \
-a \
-O 24
