#!/bin/bash --login
#PBS -l walltime=30:00:00
#PBS -l select=1:ncpus=2
#PBS -N loo
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate st2

INP="sourcetracker/loo_filtered.biom"
MAP_DIR="~/sourcetracker/maps_loo"


/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/moist_map.tsv \
--loo -o ~/sourcetracker/moist_loo

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/Nitrogen.tsv \
--loo -o ~/sourcetracker/nitrogen_loo

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/ph_map.tsv \
--loo -o ~/sourcetracker/ph_loo

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/Phosphorus.tsv \
--loo -o ~/sourcetracker/Phosphorus_loo

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/Potassium.tsv \
--loo -o ~/sourcetracker/Potassium_loo

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i $INP \
-m ~/sourcetracker/maps_loo/veget_map.tsv \
--loo -o ~/sourcetracker/veget_loo




source deactivate
