#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N phylogeny_clearcut
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
source activate qiime1
export TMPDIR=~/qiime_tmp



/usr/bin/time -f %e make_phylogeny.py \
-i ~/18/filter_align/rep_set_aligned_pfiltered.fasta \
-o ~/18/tree/my_tree_clearcut.tre \
-l ~/18/tree/tree_clearcut.log \
-t clearcut

source deactivate
