#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=16
#PBS -N pick_silva
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e \
pick_closed_reference_otus.py \
-r ~/ext_data/silva_db/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-i ~/18/split_data/seqs.fna \
-o ~/18/silva_otus \
-t ~/ext_data/silva_db/taxonomy/16S_only/97/majority_taxonomy_7_levels.txt \
-a \
-O 8

source deactivate
