#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N pick_rep
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e \
pick_rep_set.py \
-f ~/18/split_data/seqs.fna \
-i ~//18/silva_otus/uclust_ref_picked_otus/seqs_otus.txt \
-r ~/silva_db/rep_set/rep_set_16S_only/97/silva_132_97_16S.fna \
-o ~/18/rep_set.fna

source deactivate
