#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N procrustes
#PBS -A d411-training

echo "Loading environment and stuff"

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

echo "Running analysis"

/usr/bin/time -f %e \
transform_coordinate_matrices.py \
-i 18/core_div/bdiv_even600/unweighted_unifrac_pc.txt,18/core_div/bdiv_even600/weighted_unifrac_pc.txt \
-r 999 \
-o ~/18/procrustes_results/

echo "Plotting results"

/usr/bin/time -f %e \
make_emperor.py \
-c \
-i ~/18/procrustes_results/ \
-o ~/18/procrustes_results/plots/ \
-m ~/18/map_corrected.tsv

source deactivate
