#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N insert_name
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e \


source deactivate
