#!/bin/bash --login
#PBS -l walltime=50:00:00
#PBS -l select=1:ncpus=2
#PBS -N batch_sourcetrack
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
module load R-3.3.1-gcc-6.2.0-zjrjm3s
export TMPDIR=~/qiime_tmp
source activate qiime1

echo "Sourcetracker batch log" > ~/sourcetracker.log
echo "" >> ~/sourcetracker.log
echo "Merging OTU tables" >> ~/sourcetracker.log

/usr/bin/time -f %e -o ~/sourcetracker.log -a \
merge_otu_tables.py \
-i /lustre/home/d411/ilsenato/sourcetracker/otu_table.biom,/lustre/home/d411/ilsenato/sourcetracker/emp_otu.biom \
-o ~/sourcetracker/merged.biom

echo "Filter table according to map" >> ~/sourcetracker.log

/usr/bin/time -f %e -o ~/sourcetracker.log -a \
filter_otus_from_otu_table.py \
-i ~/sourcetracker/merged.biom \
-e ~/sourcetracker/parsed_map.tsv \
-o ~/sourcetracker/merged_filtered_name.biom


echo "Filter OTU table" >> ~/sourcetracker.log

/usr/bin/time -f %e -o ~/sourcetracker.log -a \
filter_otus_from_otu_table.py \
-i ~/sourcetracker/merged_filtered_name.biom \
-o ~/sourcetracker/filtered_merged.biom \
-s 7


echo "Convert table to tsv" >> ~/sourcetracker.log

/usr/bin/time -f %e -o ~/sourcetracker.log -a \
biom convert --to-tsv \
-i ~/sourcetracker/filtered_merged.biom \
-o ~/sourcetracker/filtered_merged.tsv


source deactivate
