#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N batch_sourcetrack
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

echo "Sourcetracker batch log" > ~/sourcetracker/batch.log
echo "" >> ~/sourcetracker/batch.log
echo "Merging OTU tables" >> ~/sourcetracker/batch.log

/usr/bin/time -f %e -o ~/sourcetracker/batch.log -a \
merge_otu_tables.py \
-i /lustre/home/d411/ilsenato/sourcetracker/otu_table.biom,/lustre/home/d411/ilsenato/sourcetracker/emp_otu.biom \
-o ~/sourcetracker/merged.biom

echo "Filter table according to map" >> ~/sourcetracker/batch.log

/usr/bin/time -f %e -o ~/sourcetracker/batch.log -a \
filter_otus_from_otu_table.py \
-i ~/sourcetracker/merged.biom \
-e ~/sourcetracker/parsed_map.tsv \
-o ~/sourcetracker/filtered_name.biom


echo "Filter OTU table" >> ~/sourcetracker/batch.log

/usr/bin/time -f %e -o ~/sourcetracker/batch.log -a \
filter_samples_from_otu_table.py \
-i ~/sourcetracker/filtered_name.biom \
-o ~/sourcetracker/result.biom \
-s 500


source deactivate
