#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N filter_sourcetrack
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

echo "Filter OTU table" >> ~/sourcetracker/batch.log

/usr/bin/time -f %e -o ~/sourcetracker/batch.log -a \
filter_samples_from_otu_table.py \
-i ~/sourcetracker/merged.biom \
-o ~/sourcetracker/filtered.biom \
--sample_id_fp ~/sourcetracker/parsed_map.tsv \


source deactivate
