#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N filter_sample
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

echo "SampleID is - $sample"

/usr/bin/time -f %e \
filter_otus_by_sample.py \
-i ~/18/silva_otus/uclust_ref_picked_otus/seqs_otus.txt \
-f ~/18/split_data/seqs.fna \
-s $sample \
-o ~/18/filtered_otus/$sample

source deactivate
