#!/bin/bash --login
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=2
#PBS -N merge
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e \
merge_otu_tables.py \
-i /lustre/home/d411/ilsenato/sourcetracker/otu_table.biom,/lustre/home/d411/ilsenato/sourcetracker/filtered_7.biom \
-o ~/sourcetracker/merged.biom

source deactivate
