#!/bin/bash --login
#PBS -l walltime=05:00:00
#PBS -l select=1:ncpus=32
#PBS -N track_source
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate st2

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i ~/sourcetracker/filtered_merged.biom \
-m ~/sourcetracker/parsed_map.tsv \
-o ~/sourcetracker/tracked \
--sink_rarefaction_depth 600 \
--jobs 16


source deactivate
