#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=2
#PBS -N loo_sourcetracker
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate st2

/usr/bin/time -f %e \
sourcetracker2 gibbs \
-i ~/sourcetracker/result.biom \
-m ~/sourcetracker/parsed_map.tsv \
--loo \
-o ~/sourcetracker/loo \
--sink_rarefaction_depth 700 \
--source_rarefaction_depth 700

source deactivate
