#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=2
#PBS -N split_fastq
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
export TMPDIR=~/qiime_tmp
source activate qiime1


/usr/bin/time -f %e \
split_libraries_fastq.py \
-m ~/18/map.tsv \
-i ~/18/joined/fastqjoin.join.fastq \
-b ~/18/joined/fastqjoin.join_barcodes.fastq \
-o ~/18/split_data/ \
-q 19 \
--rev_comp_barcode \
--rev_comp_mapping_barcodes \
--barcode_type 12
