#!/bin/bash --login
#PBS -l walltime=03:00:00
#PBS -l select=1:ncpus=2
#PBS -N track_sour
#PBS -A d411-training

cd $PBS_O_WORKDIR
module load miniconda/python2
module load R-3.3.1-gcc-6.2.0-zjrjm3s
export TMPDIR=~/qiime_tmp
source activate qiime1

/usr/bin/time -f %e \
Rscript ~/sourcetracker/sourcetracker_for_qiime.r \
-i ~/sourcetracker/merged.tsv \
-m ~/sourcetracker/parsed_map.tsv

source deactivate
